sonar.projectKey=LedgerHQ_ts-libs
sonar.projectName=ts-libs
sonar.sourceEncoding=UTF-8
sonar.sources=libs
sonar.exclusions=**/node_modules/**,\
**/coverage/**,\
**/.nx/**,\
**/lib/**,\
**/lib-es/**,\
**/jest.config.ts,\
**/*.test.ts,\
**/__tests__/**,\
**/__mocks__/**
sonar.javascript.lcov.reportPaths=lcov.info
sonar.testExecutionReportPaths=sonar-executionTests-report.xml
sonar.typescript.tsconfigPaths=tsconfig.base.json,libs/**/tsconfig.json
sonar.organization=ledger
sonar.newCode.referenceBranch=develop
