name: "[Release] Publish Packages"
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FORCE_COLOR: "1"

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  release:
    name: Build and Publish Release
    # JFrog is accessible only from a Ledger private runner
    runs-on: ${{ vars.RELEASE_RUNNER || 'public-ledgerhq-shared-medium' }}
    environment: release
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0

      - uses: LedgerHQ/ts-libs/.github/actions/jfrog-npm-auth@develop
        with:
          registry: ${{ vars.ARTIFACTORY_URL }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build libraries
        run: pnpm build

      - uses: LedgerHQ/ts-libs/.github/actions/jfrog-npm-auth@develop
        with:
          registry: ${{ vars.ARTIFACTORY_PUBLISH_URL }}

      - name: Publish packages
        run: pnpm exec changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
