name: "[Release] Publish Packages"
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run (print what would be published, no actual publish)"
        type: boolean
        default: false

env:
  FORCE_COLOR: "1"
  NPM_REGISTRY: ${{ vars.NPM_REGISTRY }}

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  release:
    name: Build and Publish Release
    # JFrog is accessible only from a Ledger private runner
    runs-on: ${{ vars.RELEASE_RUNNER || 'public-ledgerhq-shared-medium' }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build libraries
        run: pnpm build

      - name: Login to JFrog (OIDC)
        id: jfrog-login
        uses: LedgerHQ/actions-security/actions/jfrog-login@3868be0ef1ec8722fbdb2c6cda90f739cbfc742d # actions/jfrog-login-1

      - name: Configure npm registry
        env:
          NPM_REGISTRY_TOKEN: ${{ steps.jfrog-login.outputs.oidc-token }}
        run: |
          cat << EOF >> .npmrc
          registry=https://${NPM_REGISTRY}/
          //${NPM_REGISTRY}/:_authToken=${NPM_REGISTRY_TOKEN}
          EOF

      - name: Publish packages
        run: |
          if [ "${{ inputs.dry_run }}" = "true" ]; then
            pnpm release -- --dry-run
          else
            pnpm release
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
